name: Build & Publish RSS

on:
  workflow_dispatch:
    inputs:
      period:
        type: choice
        options: [weekly, daily]
        default: weekly
        description: "Digest period"
  schedule:
    - cron: "0 1 * * 1"   # 每周一 01:00 UTC；需要每日就改成 "30 7 * * *"

jobs:
  rss:
    runs-on: ubuntu-latest
    permissions:
      contents: read   # 读本仓库即可
    env:
      # Notion（与你现有的保持一致）
      NOTION_TOKEN:       ${{ secrets.NOTION_TOKEN }}
      NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}

      # 复用你脚本的参数
      PERIOD:   ${{ github.event.inputs.period || 'weekly' }}
      TZ:       America/Toronto

      # Feed 元信息（可按需改）
      FEED_TITLE: "JM's Picks · Weekly Digest"
      FEED_LINK:  "https://jianmeng.notion.site/…"    # 你的 Notion 导航页/主页
      FEED_DESC:  "精选来自 JM 的 Notion 电子书架"
      FEED_PATH:  "docs/feed.xml"

      # 目标公开仓库信息（改成你的）
      TARGET_OWNER: "<你的GitHub用户名>"
      TARGET_REPO:  "jm-digest-rss"
      TARGET_BRANCH: "main"

    steps:
      - name: Checkout (private repo)
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install notion-client requests

      - name: Generate RSS
        run: |
          python rss_digest.py
          test -f docs/feed.xml && echo "Feed generated."

      # 把目标公开仓库检出到子目录 out/
      - name: Checkout target public repo
        uses: actions/checkout@v4
        with:
          repository: ${{ env.TARGET_OWNER }}/${{ env.TARGET_REPO }}
          token: ${{ secrets.RSS_PUBLISH_TOKEN }}
          path: out
          ref: ${{ env.TARGET_BRANCH }}

      - name: Copy feed.xml into target repo /docs
        run: |
          mkdir -p out/docs
          cp -f docs/feed.xml out/docs/feed.xml

      - name: Commit & push to public repo
        run: |
          cd out
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/feed.xml
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: update RSS feed ($(date -u +'%Y-%m-%d %H:%M:%S UTC'))"
            git push origin ${{ env.TARGET_BRANCH }}
          fi

      - name: Show public feed URL
        run: |
          echo "Public RSS: https://${{ env.TARGET_OWNER }}.github.io/${{ env.TARGET_REPO }}/feed.xml"
